apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: worker-scaledobject
    namespace: hash-cracking
spec:
    scaleTargetRef:
        name: worker
    minReplicaCount: 0
    maxReplicaCount: 4
    pollingInterval: 30
    cooldownPeriod: 60
    triggers:
        -   type: rabbitmq
            metadata:
                protocol: amqp
                queueName: task.queue
                mode: QueueLength
                value: "5"
            authenticationRef:
                name: worker-rabbitmq-auth
