apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
    name: worker-rabbitmq-auth
    namespace: hash-cracking
spec:
    secretTargetRef:
        -   parameter: host
            name: keda-rabbitmq-secret
            key: host
        -   parameter: username
            name: keda-rabbitmq-secret
            key: username
        -   parameter: password
            name: keda-rabbitmq-secret
            key: password
