server:
    port: 8080

spring:
    application:
        name: manager

    data:
        mongodb:
            host: localhost
            port: 27017
            database: hashdb
            auto-index-creation: true

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

app:
    queue:
        retry:
            delay-ms: 10000
    taskSplitter:
        frequency: 5000
