apiVersion: v1
kind: Secret
metadata:
    name: keda-rabbitmq-secret
    namespace: hash-cracking
type: Opaque
stringData:
    host: amqp://rabbitmq.hash-cracking.svc.cluster.local:5672/
    username: guest
    password: guest
